<template>
  <div class="flex mb-8 gap-2">
    <!-- Skills:
    <UBadge @click="filter" class="badge" :ui="{ rounded: 'rounded-full' }">  <UIcon  name="i-heroicons-check" class="w-5 h-5" />
       Docker</UBadge>
    <UBadge class="badge" :ui="{ rounded: 'rounded-full' }">Vue.js</UBadge>
    <UBadge :ui="{ rounded: 'rounded-full' }">Laravel</UBadge>
    <UBadge :ui="{ rounded: 'rounded-full' }">Laravel</UBadge>
    <UBadge :ui="{ rounded: 'rounded-full' }">Project 3</UBadge> -->
  </div>

  <div data-aos="fade-leftn" class="grid md:grid-cols-2 gap-8 mx-auto">

    <Projects2Project v-for="project in projects" :key="project.id" :id="project.id" :description="project.description"
      :title="project.title" :github="project.github" :skills="project.skills" :img="project.img"
      :more="project.more" />
  </div>
</template>

<script setup>
// let skills=ref([
//   {
//     id:1,
//     text:'Laravel'
//   },
// ])
let projects = ref([
  {
    id: 1,
    title: "Vue.js And Laravel Dashboard",
    description:
      "This is an Learning web app where teachers create courses and attach different media formats for students. It contains also a chat section where teachers and students can chat each other.",
    github: "https://github.com/islem143/Elearning-web-app",
    img: "/img/ws_dashboard.webp",
    skills: [
      "Vue.js",
      "Laravel",
      "Docker",
      "Nginx",
      "Aws",
      "RL Database",
      "Ux/Ui"
    ],
    more: true
  },

  {
    id: 3,
    title: "Network Attack Visualisation Using The ELK Stack",
    description:
      "This is a system for visualizing attacks generated by IDS where this data is sent through the ELK stack to be processed, stored and finally visualized in a web dashboard so security engineers can have insights about their organization security.",
    github: "https://github.com/islem143/PFE_S",
    img: "/img/vrhost.webp",
    skills: [
      "Docker",
      "Ansible",
      "Suricata IDS",
      "Virtualisation",
      "Linux",
      "Automations",
    ],
    more: true
  },
  {
    id: 4,
    title: "File manager",
    img: "/img/file_manager.webp",
    description: "A google drive clone.",
    github: null,
    skills: ["Vue", "Larave", "Design"],
    more: true
  },
  {
    id: 2,
    title: "E-learning WebApp",
    description:
      "This is an Learning web app where teachers create courses and attach different media formats for students. It contains also a chat section where teachers and students can chat each other.",
    github: "https://github.com/islem143/Elearning-web-app",
    img: "/img/home.webp",
    skills: [
      "Vue.js",
      "Laravel",
      "Docker",
      "Nginix",
      "Redis",
      "Websockets",
      "RL Database",
    ],
    more: true
  },
  {
    id: 5,
    title:
      "Swarm Robots Self Shape Formation Using Deep Reinfocement Learning ",
    description:
      "My Master's degree final year project. Where different robots try to form geometric shapes using deep reinforcement learning algorithms",
    github: "https://github.com/islem143/PFE-MASTER",
    skills: ["DL", "ML", "RL", "Python", "Ros", "Robotics", "Tensorflow"],
    more: false
  },
]);
const filter = () => {
  projects.value = projects.value.filter(i => i.id == 1)
};
</script>
